# Generated by Django 5.1 on 2024-08-23 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="длительность привычки"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_pleasant",
            field=models.BooleanField(
                default=False, verbose_name="признак приятной привычки"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="is_public",
            field=models.BooleanField(
                default=False, verbose_name="признак публичности"
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="related_habit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="habits.habit",
                verbose_name="Связанная привычка",
            ),
        ),
        migrations.AddField(
            model_name="habit",
            name="reward",
            field=models.CharField(
                blank=True, max_length=300, null=True, verbose_name="вознаграждение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="time_habit",
            field=models.TimeField(
                help_text="HH:MM",
                verbose_name="время, когда необходимо выполнять привычку",
            ),
        ),
    ]
