# Generated by Django 5.1 on 2024-08-23 10:24

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0002_habit_duration_habit_is_pleasant_habit_is_public_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="habit",
            name="when_do_habit",
            field=models.DateTimeField(
                default=datetime.datetime.now,
                verbose_name="время, когда необходимо выполнять привычку",
            ),
        ),
    ]
