# Generated by Django 5.1 on 2024-08-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0003_habit_when_do_habit"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="when_do_habit",
        ),
        migrations.AddField(
            model_name="habit",
            name="frequency",
            field=models.SmallIntegerField(
                default=1, verbose_name="Периодичность выполнения привычки (дней)"
            ),
        ),
    ]
