# Generated by Django 5.1 on 2024-08-28 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("habits", "0005_alter_habit_frequency"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="habit",
            name="period",
        ),
        migrations.AlterField(
            model_name="habit",
            name="duration",
            field=models.DurationField(
                blank=True, null=True, verbose_name="Время на выполнение"
            ),
        ),
        migrations.AlterField(
            model_name="habit",
            name="frequency",
            field=models.PositiveSmallIntegerField(
                default=1,
                help_text="Привычку выполнять каждые * дней",
                verbose_name="Периодичность выполнения привычки (дней)",
            ),
        ),
    ]
